### ISSUE TITLE
Missing dependencies / Incomplete install instructions

### ISSUE THREAD

**Issue by Xpktro** [gibber-cc/gibberwocky.midi#1]
Hello! First of all, I just found this project and started using it right away, is very fun and a straightforward way to get livecoding done :)

I want (where possible) to contribute maybe fixing some bugs or finishing/adding some interesting things, however I can't get the current master repo to work. The instructions just say that npm install (into a `client` folder that doesn't exist and I assumed to be the project root) and gulp is enough, and even though the npm dependencies install correctly, the `gulp build` command gives the following output:

```
> gulp build
[23:10:44] Using gulpfile ~/code/gibberwocky.midi/gulpfile.js
[23:10:44] Starting 'build'...
[23:10:44] Finished 'build' after 4.76 ms
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module './wavePattern.js' from '/Users/moises/code/gibberwocky.midi/js'
    at /Users/moises/code/gibberwocky.midi/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/Users/moises/code/gibberwocky.midi/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/moises/code/gibberwocky.midi/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/moises/code/gibberwocky.midi/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
```

Which is caused by a require to `wavePattern.js` that in fact doesn't exist in this project, and also I noted some other dependencies like `genish.js` are missing too.

It would be great to have updated build instructions for fellow developers to use and making this project grow :)

**Comment by charlieroberts** [comment]
Hi Moisés,

It looks like I accidentally pushed some commits that weren't ready to go live (wavePattern.js). genish.js should definitely be a dependency though. I'll try and clean all this up tomorrow...  I need to start working on the wave patterns again for an upcoming performance anyways. They will be fun when finished...

Thanks for the bug report; looking forward to more feedback / contributions! - Charlie

**Comment by charlieroberts** [comment]
Just added wavePattern and included genish.js as a dependency. Let me know if it builds for you now.

**Comment by Xpktro** [comment]
Hello Charlie. Thanks for that lighting-fast update! In fact I'm interested in fixing the Score object. some of the performances I'm thinking of would be nice with the Score working :)

I tried reinstalling the dependencies and even when genish.js is being downloaded, `gulp build` still doesn't seem to work, now by telling me `genish.js` is nowhere to be found :(

```
> gulp build
[00:10:19] Using gulpfile ~/code/gibberwocky.midi/gulpfile.js
[00:10:19] Starting 'build'...
[00:10:19] Finished 'build' after 4.72 ms
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'genish.js' from '/Users/moises/code/gibberwocky.midi/js'
    at /Users/moises/code/gibberwocky.midi/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/Users/moises/code/gibberwocky.midi/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/moises/code/gibberwocky.midi/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/moises/code/gibberwocky.midi/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/moises/code/gibberwocky.midi/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/moises/code/gibberwocky.midi/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
```
I can't figure out what can be happening, the gulpfile seems to be in good shape.

```
> npm ls | grep genish
├─┬ genish.js@0.2.3
```

**Comment by charlieroberts** [comment]
I'm having some problems getting it to build as well. I updated genish.js with a fix that might solve the problem you identified, but there still seems to be other gulp issues whenever I try to do a fresh install / compile. I'll keep working on it.

You mentioned bugs in Score... are you talking about the looping?

**Comment by Xpktro** [comment]
The project is now building correctly and seems to be working as expected (at least the basic sequencing method I'm using now :)) 

Yes, I was talking about the loop problem with Score. For the little time I had for tracing it, it seems to be a problem with codemirror, right? :)

**Comment by charlieroberts** [comment]
Great! Then I guess problem solved with compiling :) I was getting some really, really strange errors... my guess is because I have a development copy of genish.js installed via npm link, maybe that was somehow conflicting with the versions that were being grabbed via npm install??? I don't know.

It looks like there are annotation problems that I can take care of... but I don't think that's only problem. FYI you can also use a Seq:

```js
funcs = [
  ()=> log( 0 ),
  ()=> log( 1 ),
  ()=> log( 2 )
]

times = [1,1,2]

s = Seq( funcs, times ).start()
```

...although the annotations create weird extraneous parenthesis, the code will actually run fine. I'm going to close this issue and start one that is Score specific.
